Vagrantfile
This problem appeared suddenly. For more info see https://github.com/rvm/rvm/issues/3110
=> Fix GPG key error in scripted installation of RVM

_config.yml
As mentioned in #55, this makes triple backticks work as expected.
Left is expected existing, right is expected new:
=> Support triple backticks

css/main.css
In `main.css` file,`<p>` has a default margin top value-`30px`;it causes this result:if `<p>` is in `<blockquote>`,the default value makes the blockquote looks a little strange!       
So,I added `blockquote p{margin:0}` to `main.css` file!      
This is my first time to send pull request,hope I didn't make any mistakes!
=> Reset margin-top of <p>-in-<blockquote>

index.html
Since the truncate happens first, parts of HTML tags are cut in ways which will not be caught by the strip_html and xml_escape string filters. Switching the order of the filters fixes this issue. An example of this problem can be seen in the Test Mardown post.
=> Change order of post excerpt processing

README.md, _config.yml, _layouts/post.html, _layouts/tag_index.html, _plugins/_tag_gen.rb, _posts/2015-01-04-first-post.md, _posts/2015-01-15-pirates.md, _posts/2015-01-27-dear-diary.md, css/main.css, index.html
Tags will be displayed as plain text by default. If user is not deploying on GitHub pages, they can set `link-tags: true` in `_config.yml` to tell Jekyll to automatically create a new page for each tag that lists all posts that have that tag. I've added a brief explanation under "Advanced featrues" in the README.
=> Add tag options

_posts/2015-02-20-test-markdown.md, css/main.css, css/pygment_highlights.css
I created similar styling for code blocks with line numbers. The styling for code blocks without line numbers should be the same.
=> Add styling for code blocks with line numbers

_config.yml, _includes/footer.html
(Xing is similar to LinkedIn, popular in Germany)
fontawesome provides a xing symbol.
=> Add link to Xing profile to footer

index.html
In index.html, there is a line for post excerpts:
```
{{ post.content | strip_html | xml_escape | truncatewords: 50 }}
```
But Chinese and Japanese don't contain spaces in articles, so it's not possible to truncate 50 words from that kind of posts.
I made a test shown in the image. If there aren't enough spaces in Chinese posts, the whole article is used as the excerpt.
Would you consider using [post.excerpt](https://jekyllrb.com/docs/posts/#post-excerpts) instead?
```
{{ post.excerpt | strip_html | xml_escape | truncatewords: 50 }}
```
This is how it looks.
=> use post.excerpt instead of post.content

_config.yml, index.html
Uses the excerpt only to a maximum number of words on the index page. Moved out maximum number of excerpt words value to configuration.
=> Fix show/hide of Read Me link on index page

_config_dev.yml, serve
This uses addtional _config_dev.yml which sets
`url: "http://localhost:4000"`
So you can run the blog on your local pc without changing the original _config.yml.
Use with this command(the serve file):
`bundle exec jekyll serve --config _config.yml,_config_dev.yml`
To use the shortcut, make the script executable:
`chmod +x serve`
And then run it
`./serve`
Congrats, you run now your jekyll site locally without needing to change _config.yml to point it out to localhost!
=> quickfix to run blog on localhost without changing _config.yml

_config.yml, _includes/gtm_body.html, _includes/gtm_head.html, _includes/head.html, _layouts/base.html
Google Tag Manager (GTM) is commonly used for managing all Digital Analytics tracking solutions in one place.
It was recommended by GTM to add the `<script>` tag as high in the <head> of the page as possible, and to add `<noscript>` tag immediately after the opening <body> tag.
=> Add Google Tag Manager Integration

README.md, _includes/ext-css.html, _includes/ext-js.html, _includes/footer-scripts.html, _includes/head.html
Modify `ext-js` and `ext-css` YAML front matter parameters to take
`href` and `sri` values. If `sri` is set, add to integrity attribute on
script/link element loading external JavaScript/CSS.
Existing behaviour is maintained if `href`/`sri` are not used.
For more information on SRI, see:
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity
=> Add Subresource Integrity (SRI) support

_includes/footer.html, _includes/social-share.html
`aria-hidden="true"` on icons and `class="sr-only"` on the icon replacement text.
Sources:
- http://fontawesome.io/accessibility/
- https://www.w3.org/WAI/GL/wiki/Using_aria-hidden%3Dtrue_on_an_icon_font_that_AT_should_ignore#Description
Verified it works, served locally and at http://eusebius.tech/aboutme/:
```bash
lynx http://eusebius.tech/aboutme/
```
=> Icon replacement text for screen-reader/text-only browsing, fixes #176

Gemfile.lock
When building locally, json 1.8.3 fails to install when running bundle install. Version 2.1.0 works.
=> Update json gem to 2.1.0

_config.yml, _data/SocialNetworks.yml, _includes/footer.html
- merged config keys for social network data and activation control in `_config.yml`
- adds simple static data file `_data\SocialNetworks.yml` for link defintions
- simplified the `footer.html`
I tried to keep this as simple as possible for maintainers and user. Unfortunately it's not possible to create nested liquid tags. So I hat to use an ugly hybrid way to compose the links to social networks which does not match the target link pattern: `<basURL><UserContent>`
- This should fix #277
=> Adds simple Social Network Link / Social Networks Data definition

css/main.css
fixes #268
- clear `:focus` rule - prevent #ddd color linger on desktop
- clear `:hover` rule - prevent #ddd color linger on touchscreen
- add `aria-expanded="true"` rule - set #ddd color when expanded
after merging, I'll work on #256
=> Remove :focus and :hover rules from .navbar-toggle

CHANGELOG.md, _config.yml, css/main.css
=> Set colors using Jekyll variables (without conditionals) in main.css

CHANGELOG.md, Dockerfile, Gemfile.lock, README.md
Conversation here: https://github.com/daattali/beautiful-jekyll/issues/302#issuecomment-357528536
In jennydaman/beautiful-jekyll, I have to branches. :readme-dock is upstream to :dock. All I changed was the wording of README.md to match my taste. If you don't like it, I'll open a PR for :dock instead.
https://github.com/jennydaman/beautiful-jekyll/compare/dock...jennydaman:readme-dock
Unrelated: In my last PR I added a comment that suggests CSS gradients can be used as colors. That's true, and it looks slick. https://twlinux.github.io/
Unfortunately, it turns out replacing `background` with `background-color` removes compatibility with gradients. Oops. Do you want me to change that?
=> Simplify Docker use :whale:

_config.yml, _includes/footer.html, _includes/head.html, _includes/matomo.html
Some users don't like using Google Analytics. Alternatively they use the open-source tracking suite Matomo (aka Piwik). I added 3 simple config keys to set up the tracking with an existing Matomo instance.
All you need is:
- Matomo Site ID
- Matomo Instance URI
- Enable / Disable the Opt-Out feature.
- Restructured the config keys section in `_config.yml`. There is now a dedicated *Web Statistics Section*
- contains Google and Matomo preferences
- added `matomo.html` include file with the JS tracking code
- added Do-Not-Track link in footer if Opt-Out is set. This will open a new page in the browser language.
- tracking code in header headed if keys set.
@daattali : Maybe you have got an other idea where and how to add the Do-Not-Track link.
fixes #309
=> Adds Matomo (aka Piwik) integration

Dockerfile
Just technicalities for the die-hard perfectionist...
The Dockerfile from the image jekyll/jekyll is here: https://github.com/envygeeks/jekyll-docker/blob/d056a3bfa57763b3d1717aeb2ad1972c7d05b3b9/repos/jekyll/Dockerfile
So many configurations in our Dockerfile are inherited, making the lines I have removed unnecessary.
The issue concerning dependencies is resolved by ` COPY Gemfile.lock .`
It is preferable to define `CMD` instead of `ENTRYPOINT` because of [this wrapper script](https://github.com/envygeeks/jekyll-docker/blob/d056a3bfa57763b3d1717aeb2ad1972c7d05b3b9/repos/jekyll/Dockerfile#L171-L172).
=> Even simpler Dockerfile

README.md
$PWD needs to be surrounded in quotes so that the commands work when any folder in the path has a space in it.
Currently if someone runs the command as-is, and their folder path has a space in it, they will get the build error message `"docker build" requires exactly 1 argument` build and run error message `docker: invalid reference format` during run.
=> Readme.md: fix instructions for dirs with spaces

_config.yml, _includes/gtag.html, _includes/head.html
Google Analytics has a new type of default `<script>` tag called `gtag`. This PR adds support for that.
=> Add gtag support for Google Analytics

_includes/nav.html
Removed the extra space after {{ site.url }} and before "
This prevents an error "This site can’t be reached" when clicking the Avatar to return home.
Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.
If your intention is to submit a Pull Request, please describe what your pull request achieves.
Thank you!
=> Fixed avatar img link on LINE51 (contained space)

_data/ui-text.yml
The word for Address in German is 'Adress' with only one d.
The 'Sie' is very formal. In online conversation and Blog is 'Du' common.
=> German translation improvement

README.md, _config.yml
Hi,
Thanks a lot for including JustComments in Beautiful Jekyll! I am the creator of the system and I'd like to suggest a little change: rename `just-comments` to `JustComments` when referring to the service name. Great work with Beautiful Jekyll!
Best regards,
Alex
=> Rename just-comments to JustComments

Dockerfile
Patch for docker build error: 
```
There was an error while trying to write to /srv/jekyll/Gemfile.lock. 
It is likely that you need to grant write permissions for that path.
```
=> Add permission for jekyll user on Gemfile in Docker

Gemfile
Update github-pages plugin from version 193 to 197.
Fix #457
Fix #385
=> Update github-pages plugin

404.html, _data/SocialNetworks.yml, _includes/footer-scripts.html, _includes/footer.html, _includes/head.html, _includes/header.html, _includes/nav.html, _includes/navbarlink.html, _includes/staticman-script.html, _layouts/post.html, css/main.css, index.html
For Github project pages, site background image would fail to load because baseurl is not prepended to image path.
Also switch globally to `relative_url` for all baseurl prepends, which is more robust than custom URL mangling, as `relative_url` would sanitize baseurl before prepending.
=> Fix showing background img with non-empty baseurl

README.md, _config.yml, _includes/fb-comment.html, _includes/footer-minimal.html, _includes/footer.html, _includes/head.html, _includes/nav.html, _includes/social-share.html, feed.xml, tags.html
This is required fixes for absolute links. To use it, one would need to either:
1. Change `site.url` to new setting (remove project component), or
2. Simply delete `url` and `baseurl` altogether and let Github autoguess them
FAQ is not added yet, since I'm not sure how @daattali you would like
to express this issue inside FAQ. Suppose it can be added later?
=> Abs link patch

css/main.css, css/pygment_highlights.css
Code block bg adopts to custom user bg color instead of using
hardcoded color, preserving original design as much as possible ( Closes #512 )
------
Some background info:
- White space related change described in #117 is already available from bootstrap, so I removed it
- Lineno related styles moved to main css
=> Refactor code block styles

README.md, _config.yml, staticman.yml
When `moderation: true` in `staticman.yml`, a PR containing a branch like `staticman_5525bf80-055f-11e9-a156-295f601b09e8` is created.  After merging such PR, such branch would become useless.  We have better offer an advice for automatic deletion after merging to avoid such branches from piling up.
The technical details consist of several steps.  I redirect interested users to the [relevant page in the official doc](https://staticman.net/docs/webhooks), and adding necessary adaptations.
The current `endpoint` parameter is borrowed from `_includes/comments.html` in https://github.com/mmistakes/minimal-mistakes/pull/1845.  Due to [Staticman's URL scheme change introduced in v3](https://mmistakes.github.io/minimal-mistakes/docs/configuration/#staticman-v3), one has to add an extra parameter …
=> Staticman documentation enhancement

_includes/footer-scripts.html
Fixes #342
This request simply changes the order scripts are loaded in footer-scripts.html, which addresses an issue where jquery and boostrap are undefined in page scripts.
The loading order proposed is **common-ext-js -> common-js -> ext-js -> page-js** because common scripts should be loaded before page scripts, and external scripts should be loaded before local scripts for the same reason, which is that local scripts may want to reference APIs from external sources.
=> Fix JavaScript loading order

_config.yml, _includes/header.html, tags.html
=> Add support for customizable date format

_data/SocialNetworks.yml, _includes/footer.html
This changes `_data/SocialNetworks.yml` to use URI templates instead of a URL prefix. 
Old:
```
baseURL: "https://www.facebook.com/"
```
New:
```
urlTemplate: "https://www.facebook.com/{value}"
```
This allows to support different URL schemes without having to edit `_includes/footer.html`, e.g. Yelp's `https://{business}.yelp.com`.
Only the RSS feed is still special-cased in `_includes/footer.html`.
=> Use URI templates for social network links

_data/SocialNetworks.yml, _includes/footer.html, _includes/social-share.html, _layouts/base.html, tags.html
- uses the CSS version
- updates `_data/SocialNetworks.yml` to make the icon property include both the Font Awesome style class and the icon class, e.g. `fab fa-github`
- updates all static usages to use the new CSS classes for the Font Awesome style (`fas` = solid, `fab` = brands)
- the new version doesn't seem to be available on `maxcdn.bootstrapcdn.com`, so I used `cdnjs.cloudflare.com`; see https://cdnjs.com/about
=> Update to Font Awesome 5

README.md, _config.yml, _includes/utterances-comment.html, _layouts/page.html, _layouts/post.html
As we talk in here [add new comments - gitalk support ](https://github.com/daattali/beautiful-jekyll/pull/591),  add #591  @daattali 
Now add [utterances](https://github.com/utterance/utterances) comments widget support.
add utterances-comment.html into _includes
change post.html/ page.html link to utterances-comment.html
add utterance parameters into _config.yml and README.md docs
You can check the demo from [this website](https://colynn.github.io/aboutme/)
=> add utterances comments support

CHANGELOG.md, _config.yml, _includes/social-networks-links.html
PR follows discussion at #646 .
Making a PR with only a mastodon link. Looking forward to any comments. A tricky thing is that because mastodon is decentralised there are two things that need to be specified, the hosting instance URL and the username on said instance. I went around this by suggesting the mastodon entry in `_config.yml` be filled in such way that both can be presented as one variable.
P.S. I am not adding a matrix link in this PR because a matrix logo is not included in font-awesome currently. I have [one implementation](https://github.com/Iolaum/beautiful-jekyll/tree/dev_social_matrix) that [uses another non-related picture](https://github.com/Iolaum/beautiful-jekyll/commit/46b1e9f5c7548b0097cc16379f974fbe6930a419) and  a [second …
=> Adding Mastodon Social Network Link

CHANGELOG.md, _includes/head.html
`article` seems to be a more fitting type than `website` for blog posts. See https://ogp.me/#type_article
=> Use Open Graph type 'article' for blog posts

CHANGELOG.md, README.md, _includes/head.html, _posts/2020-02-26-flake-it-till-you-make-it.md
If `share-img` is specified use Twitter's `summary_large_image` card instead of the `summary` card.
See https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image
Additionally, this changes `share-img` to also support relative URLs. Existing posts that use absolute URLs for `share-img` don't need to be changed because absolute URLs are still supported.
A `share-img` value is added to the "Flake it till you make it" post to demonstrate the `summary_large_image` card.
=> Add support for Twitter's 'summary_large_image'

README.md, _includes/head.html
Sometimes a page subtitle isn't substantive enough to be a good value for a meta description. An optimal length for meta descriptions is usually around 150 characters, which might be too long for a pithy page subtile. In this case I added a `site.description` override that will be used only if provided. Otherwise we fallback to using the subtitle.
=> Adds page configuration for description

_config.yml, _includes/head.html
Having `page.css` is nice, but there's no way to add css for the entire site. You could just modify `main.css` with the changes you want, but that makes upgrading to the latest from upstream somewhat difficult as you have to deal with potentially complicated merge conflicts. Or you could add the additional css to each and every page, which is annoyingly tedious and human-error prone.
This PR adds a site level configuration for `site-css` that allows you to list additional css files that should be included for every page on the site.
=> Adds configuration for additional site css

beautiful-jekyll-theme.gemspec
I think this will resolve the build errors we're seeing on the latest PRs. I think one of the existing runtime dependencies must have had `kramdown-parser-gfm` as a dependency, but doesn't any longer? So adding it to our dependency list resolves the issue.
=> Kramdown parser gfm dep

CHANGELOG.md, _config.yml, _includes/head.html
Adds support for [meta theme-color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color).
=> Adds support for meta theme-color

CHANGELOG.md, _config.yml, _includes/head.html
Adds support for meta keywords. It will use the page keywords if provided, otherwise fallback to site level.
=> Adds support for meta keywords

CHANGELOG.md, _includes/head.html
Adds meta tags for `og:site_name` which will just use the existing `site.title` configuration. Slightly different than `og:title` which can be overridden on a per-page basis. Whereas `og:site_name` will _always_ just be whatever `site.title` has been configured to be.
=> Adds og:site_name support

CHANGELOG.md, assets/js/main.js
Pretty simple little bit of javascript to intelligently set the navbar class to either `navbar-light` or `navbar-dark` based on the color of the navbar that the user has configured. This will make it so that navbar elements like the hamburger menu in the mobile site view are easier to see on dark background colors.
| Before | After | Result |
| --- | --- | --- |
| ![before-spellbot](https://user-images.githubusercontent.com/1903876/90056946-89007300-dc94-11ea-8b54-888844c46a53.png) | ![after-spellbot](https://user-images.githubusercontent.com/1903876/90056959-90c01780-dc94-11ea-8a1b-07d72f3effc8.png) | actually visible now | 
| ![before-darkblue](https://user-images.githubusercontent.com/1903876/90056991-9a497f80-dc94-11ea-97ef-33acaef317d1.png) | …
=> Automatically set navbar light/dark based on color

CHANGELOG.md, _includes/head.html
Fixes https://github.com/daattali/beautiful-jekyll/issues/744
=> fix(#744): Escape special characters in title

CHANGELOG.md, assets/css/beautifuljekyll.css
Resolves https://github.com/daattali/beautiful-jekyll/issues/749
~~Changing the margin-top just a bit seems to fix the issue on Safari while leaving Firefox and Chome nearly unchanged.~~
Edit: Updated the PR to use the better suggestion from @daattali.
=> Fix margin top alignment issue on Safari

_config.yml, assets/js/staticman.js, staticman.yml
1. Resolves #541
2. Update the instructions for Staticman in the sample config file `_config.yml` so that it complies with Staticman's maintainer's recommendations to
+ use self-hosted instances
+ avoid any public API instances in https://github.com/eduardoboucas/staticman/issues/317#issuecomment-565250060.
3. Seize this chance to announce the end-of-service of my "bot" @<span>staticmanlab</span> on GitHub.
1. Removes all fallback/default to my Staticman instance `staticman3.herokuapp.com`.
2. Added a brief description about
1. one-click deploy to Heroku ![Deploy](https://www.herokucdn.com/deploy/button.svg).
2. GitHub App creation: https://docs.github.com/en/developers/apps/creating-a-github-app, thanks to https://hajekj.net/2020/04/15/staticman-setup-in-app-service/.
3. Heroku app …
=> Remove references to any public Staticman API instance

CHANGELOG.md, _config.yml, _includes/cloudflare_analytics.html, _includes/head.html
Resolves #797. Cloudflare offers user privacy-preserving analytics.
=> Add support for Cloudflare analytics

_config.yml, _includes/social-networks-links.html
This adds the option to display a discord icon in the social network list.
you could either set this to for example invite/invite_code to get a link to your discord server or to users/userid to get a link to your discord profile where people could add you
apperantly this theme uses an old version of fontawesome and because of that it still displays the old discord logo
=> Add discord to supported social networks

assets/js/staticman.js
This is a follow-up of #1048 that I've raised.  I encourage others try replacing `var` by either `const` or `let` in other JS code.
Observe that in my Staticman script, once the variables are defined, they are never ~~changed~~ reassigned.
I've removed the line `var $comments = $('.js-comments');` because that's never used.  (c.f. mmistakes/minimal-mistakes#1996)
On [my fork](https://git.io/bjsm0)'s `gh-pages` branch (for [demo site](https://git.io/bjsm18)), dbde15b4's parent is a merge commit that incorporates this commit.
=> replaced `var` with `const` in Staticman script

_config.yml, _includes/social-networks-links.html
Per our earlier conversation, the discord link now will work if it is populated with "users/code", "invite/code", or "code".
I hope this is helpful.
=> Updated Discord Link

CHANGELOG.md, _config.yml, _includes/social-networks-links.html
GitLab is also in font-awesome so adding support for it is pretty much a copy-paste from the GitHub entry. I just added it for my own website, but it should probably live upstream.
=> Add GitLab to the list of social media sources

CHANGELOG.md, _config.yml, _includes/social-networks-links.html
Adds Bluesky as another possible social network link. 
Note I used the same FontAwesome icon (a simple square!) that Bluesky uses on its homepage:
https://blueskyweb.xyz/
The icon is discussed further here:
https://github.com/FortAwesome/Font-Awesome/issues/19810
=> Add Bluesky to social network links

CHANGELOG.md, _layouts/base.html, assets/css/beautifuljekyll.css
Makes the footer stick to the bottom when the content isn't enough to push the footer past the screen using CSS grids.
=> Made the footer stick to the bottom; fixes #576

_config.yml
As the title implies, this PR adds a itch.io entry to the social network links along with all the others that are commented out. I actually didn't know that this template supported itch.io as social network link, since I only looked in the `_config.yml` and though the ones present there were the only ones available. So I think adding it there will make it somewhat less obscure.
=> Add itch.io social network link to the commented out entries

CHANGELOG.md, _config.yml, _includes/head.html
This PR adds a site option called `title_on_all_pages` - it adds the `site.title` to the end of all page titles (separated by `|`), unless the `site.title` and `title` are the same string (usually on home pages).
This still contains my commit from #1270 but if you like the idea, and the variable name, I'll tidy it up and remove that commit before you accept it. No worries if you don't want this option in your theme!
=> Add a title-on-all-pages site option

beautiful-jekyll-theme.gemspec
Hi @daattali 
Versions of the `github-pages` gem after 229 depend on `kramdown` version 2.4.x. This PR relaxes the version constraint to ensure people can update to the latest version of `github-pages`. It should still work exactly the same with earlier versions too.
=> Relax version constraint for kramdown

.github/workflows/ci.yml, Appraisals, beautiful-jekyll-theme.gemspec
Hi @daattali - instead of papering over the issue with my previous fix in #1270, I decided to do a deep dive into why GitHub Actions was failing with the relaxed version constraint and fix that instead.
The reason is because it depended on the Docker image `jekyll/builder:3.8`, which installs Jekyll 3.8.x, but the version constraint required at least 3.9.3. This meant bundler would install the latest version that matched the constraint over the top of the 3.8.x in the image. If that was a 4.x then it would fail because 4.x depends on `sass-embedded` which is not supported by the version of Rubygems in the `jekyll/builder:3.8`. Unfortunately, [jekyll/builder is no longer maintained](https://github.com/envygeeks/jekyll-docker/issues/364) and consequently there is no image for the 3.9.x …
=> Fix GitHub Actions for Jekyll 4.x

_config.yml, _includes/social-networks-links.html
Adding Whatsapp to social networks. Especially useful on mobile devices to launch whatsapp directly with the correct phone number.
=> Added Whatsapp to social network

_config.yml, _includes/social-networks-links.html
This PR allows using a subreddit social account by prefixing the name with `r/`.
Additionally, some trailing whitespace was removed in the files I modified.
=> feat(social-links): allow subreddit

.github/workflows/ci.yml
The CI build does not respect the `relative_url` property when building from a "project" repo instead of the `.github.io` named repo.
Fixes #1373
The changes are derived from the examples here (https://github.com/actions/jekyll-build-pages) and were tested here (https://github.com/ReenigneArcher/beautiful-jekyll/pull/3). A small bug was found where those changes would not run certain plugins, such as those in a `_plugins` directory, so I reverted some of the changes, and made some tweaks in https://github.com/ReenigneArcher/beautiful-jekyll/pull/4. The changes in this repo are slightly different than from those two PRs, as the the deploy step is omitted.
The majority of people using beautiful-jekyll will probably never notice this issue because they are probably either using the repo …
=> ci(workflow): ensure relative_url is used

_includes/social-networks-links.html
Changed the social icon from a square to Bluesky's icon in font awesome
This is the screenshot of running this change locally:
=> Bluesky icon in font awesome

assets/css/beautifuljekyll.css
The social media links at the bottom of the page lack a margin-bottom meaning that when there are many of them and they spill onto a second line, there is no space between the rows, and this looks ugly. This change adds a suitable margin and also reduces the footer's overall margin-bottom to match the increase in item margin-bottom.
=> Add margin-bottom to social media links

feed.xml
The default feed.xml doesn't include the post author. If the reader you're using usually displays the author, that field gets left blank and it looks ugly. This change adds the post author to the RSS feed if it exists, or uses the site author if the post doesn't have an author, or just doesn't set it at all if no author is provided.
=> Add author to RSS feed

Gemfile
When running on Windows, wdm is required in order to properly do incremental updates and regeneration.
The tzinfo-data dependency is also reported missing (under Windows at least, with jekyll 3.9.3).
=> Add missing windows extensions
