_config.yml
Promised to check this out a long time ago! This will make it so folks can edit their posts with a WYSIWYG editor if they so desire.
=> Update to prose.io config

README.md, _config.yml, _includes/nav.html, _layouts/default.html
Hi, I'm using beautiful-jekyll for my personal site (https://hristoyankov.com) and I love it. However, I needed a way to show my avatar only in the "About me" and in the future "Personal projects" and therefore added liquid param for this.
NB: This is my first pull request I may have made some mistakes. Thank you for your understanding in advance!
=> Add conditional avatar

README.md
I finally got around to redoing my web site on the plane to ISMB. Thanks, Dean!
=> README.md: Add personal website sjackman.ca

_includes/footer.html
Issue #71 created to highlight the same.
=> Integrating Public Custom LinkedIn URL

css/main.css, css/pygment_highlights.css
=> Fix background color of numbering

_config.yml, _includes/footer.html
Can be seen at http://eusebius.tech.
[source](https://github.com/eugenius1/eugenius1.github.io)
=> Add Instagram to footer

_config.yml, _includes/head.html
I added FB app ID option, edited some social sharing details so that it can be better.
=> add fb app ID, improve social sharing descriptions

_includes/social-share.html
=> added page title in twitter social share button

README.md
Added my site under Personal Websites section.
=> Added my site on the list of personal sites

featured-users.md
added myself on the personal websites list.
=> Added my site on the personal websites list

_config.yml
=> Add build excludes

css/main.css
Fixes #215.
Also, my editor (Atom) decided to remove some trailing spaces in the file. If for some reason you want those back, please let me know.
=> Added fallback fonts to footer copyright.

README.md, _layouts/post.html, css/main.css
add badges functionality to post.html and instructions in readme yaml section
=> Badge functionality to layout/post.html

css/main.css, js/main.js
With some automatic whitespace cleanup courtesy of Atom.
=> Avatar now fades with jQuery (#293)

css/main.css
=> Fix navlinks-parent color on small screens

_config.yml
Automatically generate sitemap.xml to use with Google Search Console and improve SEO.
=> Generate sitemap.xml

Dockerfile
Container was not working because didn't have all dependencies, and change CMD command for ENTRYPOINT.
=> Container now have all proper dependencies

css/main.css
=> Fix code fence css bug when published on gh pages

_includes/head.html, css/main.css
Notch display(like iPhoneX) support
=> Notch display

_config.yml
I think that is better to use HTTPS URL..
=> Use HTTPS as default protocol of site

CHANGELOG.md, _includes/footer-scripts.html, _includes/head.html
#406 
Move the Google Analytics code to be included in the Head
=> Moved Google Analytics to the Head

_includes/google_analytics.html
- fixes issue with adding the google analytics script.
- added missing protocol in link: `https` -> https://developers.google.com/analytics/devguides/collection/analyticsjs/ 
- fixes #432 
- Not tested yet.
- waiting for reply from @Azimstech or @vlavorini
=> Fix issue with Google Analytics integration

_posts/2015-02-28-test-markdown.md
Avoid loading mixed contents warning message.
=> http -> https

_includes/staticman-script.html
Resolves https://github.com/daattali/beautiful-jekyll/pull/440#issuecomment-449878522.
My test site: https://cox-zucker.github.io/2015-02-28-test-markdown/ ([Source](https://github.com/cox-zucker/cox-zucker.github.io))
=> Fix Staticman's raw JSON response in #440

README.md
Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.
If your intention is to submit a Pull Request, please describe what your pull request achieves.
Thank you!
=> Correct typo introduced at fe40d41d

README.md, _config.yml, _includes/just_comments.html, _layouts/page.html, _layouts/post.html
Hello guys
This PR contains the integration with just-comments system. It is another alternative to Disqus and staticman.
If you want you can check an example here: https://hugo-ma-alves.github.io/2019-03-22-pihole-vodafone/
Note: I am not affiliated with just-comments. I implemented this for my page and I thought it could be useful to someone else.
=> Integration with just-comments

css/main.css
Added green a  .box-success  class.
=> Addes a .box-success class

_config.yml, _data/SocialNetworks.yml, _includes/social-share.html
Google Plus has shutted down, remove related code.
Signed-off-by: Yu-Chen Lin <npes87184@gmail.com>
=> R.I.P. Google Plus

index.html
Additional relative link fix, missing from previous PR
=> Fix post image url too

README.md
Due to inconvenience brought by massive spam comments reported in https://github.com/einsteinpy/einsteinpy.github.io/pull/25#issuecomment-504936235, perhaps we should at least give an advice on how to stop that.
=> Staticman: suggestion to use reCAPTCHA

README.md
A typo carelessly introduced in #514.  Spotted out in onweru/hugo-swift-theme#15.
=> Fixed Staticman docs typo

README.md
Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.
If your intention is to submit a Pull Request, please describe what your pull request achieves.
Thank you!
=> Had the word "and" twice in a row. Removed one of them

css/main.css
=> removed double spaces

_data/ui-text.yml
PR idem to mmistakes/minimal-mistakes#2220.
=> Remove fullstop in some Staticman UI text

index.html
I forgot to include this change in the last pull request.
=> Add support for customizable date format

_includes/just_comments.html
JustComments got a new updated UI available via `w2.js` script. I think it's good to enable it by default.
=> Use v2 for JustComments

CHANGELOG.md, _config.yml, css/main.css
- adds ability to turn off the round avatar
=> Allow to disable the round avatar

_includes/footer-minimal.html, _includes/footer.html, _includes/head.html, _includes/header.html, _includes/nav.html, css/main.css, feed.xml, index.html, tags.html
see https://github.com/daattali/beautiful-jekyll/pull/590
=> Add default values

CHANGELOG.md, _config.yml, _includes/header.html, _includes/readtime.html, css/main.css
Please note that if you are trying to update **your** website, this is the wrong place to do so. Please carefully follow the Beautiful Jekyll instructions (found at https://github.com/daattali/beautiful-jekyll#readme) and make sure you submit changes to **your** version of the project.
If your intention is to submit a Pull Request, please describe what your pull request achieves.
Thank you!
=> Adding onto #595, fixing some mobile style issues to the readtime of each post

css/main.css
I missed this. This off centers the logo by a bit
=> Misplaced css attribute

CHANGELOG.md, _config.yml, _includes/social-share.html
=> Add social share: VK

_config.yml, _includes/social-networks-links.html
Added support for google scholar and ORCID social networks.
=> Add orcid and google scholar

beautiful-jekyll-theme.gemspec
=> fix typo in gemspec

CHANGELOG.md
Adds the missing changelog items from the recent PRs. I'll update the PRs that are not merged yet to include their own updates to this file once this PR is merged and those PRs are rebased on the updated `master`.
=> Adds the missing changelog entries from some recent PRs

CHANGELOG.md, _config.yml, _includes/social-networks-links.html
#783 Submitting this PR so that the user will have an option to link their Medium profile on the website's footer.
=> Adding option for Medium Social Link at footer 

CHANGELOG.md, _includes/social-networks-links.html
=> Itch.io social link

CHANGELOG.md, _includes/social-share.html
=> Include Reddit in share options of posts

_includes/social-networks-links.html
See https://docs.joinmastodon.org/user/profile/#fields
=> Add Mastodon profile verification

_config.yml, _includes/social-networks-links.html
=> adding kaggle social link

_config.yml, _includes/social-networks-links.html
added hackerrank part in _config.yml and and _includes/social-media-networks-link.html
=> added hackerrank social media network

_includes/nav.html, assets/css/beautifuljekyll.css
Fixes #765, I also had the same issue.
Before:
After:
I also restored the small border since I found it nicer. It's up to you if you wanna leave it or not.
Works also responsive.
See https://dagnelies.github.io/passwordless-www/ for live demo.
=> Fixes #765

CHANGELOG.md, _includes/social-networks-links.html
Closes #1187  and supersedes  #1188
=> fix google scholar link construction (#1187)

CHANGELOG.md, _includes/social-networks-links.html
Fixed Yelp url bug and updated change log.
=> Yelp url bug fix (#1259)

assets/css/beautifuljekyll.css
Fixing Issue #1263, updated the search bar
=> Updated Search Bar 

_config.yml, _includes/social-networks-links.html
Add [Untappd](https://untappd.com/) social network 🍻
=> feat(social): add untappd

_config.yml, _includes/social-networks-links.html
This adds a [Strava](https://strava.com) social network link.
=> Add Strava social network link
